// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYVd--KNlSt--Duanoq4JzdxfhfdvSBSE',
    appId: '1:419101609005:web:08bc0a3207295dc79efca4',
    messagingSenderId: '419101609005',
    projectId: 'wardrobe-bd62f',
    authDomain: 'wardrobe-bd62f.firebaseapp.com',
    storageBucket: 'wardrobe-bd62f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARdgMl1T6LBe2bDFZhp6TmjH4apH8e0fk',
    appId: '1:419101609005:android:fe2b8882aad034009efca4',
    messagingSenderId: '419101609005',
    projectId: 'wardrobe-bd62f',
    storageBucket: 'wardrobe-bd62f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_zt62XeBDZ61EF6FWkySnAL0uYLc5Pgo',
    appId: '1:419101609005:ios:c2ad69f84cd5b2ab9efca4',
    messagingSenderId: '419101609005',
    projectId: 'wardrobe-bd62f',
    storageBucket: 'wardrobe-bd62f.appspot.com',
    iosBundleId: 'com.example.wardrobe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_zt62XeBDZ61EF6FWkySnAL0uYLc5Pgo',
    appId: '1:419101609005:ios:0c653e991715152f9efca4',
    messagingSenderId: '419101609005',
    projectId: 'wardrobe-bd62f',
    storageBucket: 'wardrobe-bd62f.appspot.com',
    iosBundleId: 'com.example.wardrobe.RunnerTests',
  );
}
